### ISSUE TITLE
Images on the home page are too heavy

### ISSUE THREAD

**Issue by DVLP** [ericdrowell/ElGrapho#4]
I noticed when opening your website that the skull image(el-grapho.png) didn't load instantly and checked in the network tab that it takes 300kb. Check out tinypng or some alternative command line utility for automation to reduce the image size to 100kb. Even larger one el-grapho-clusters.png takes almost 0.5MB and can be easily reduced to 110kb

**Comment by ericdrowell** [comment]
Thanks, you're right, the website is total crap.  Haven't invested much time in it yet.  Mostly been focusing on the library itself and the README for the docs.  It will eventually get spruced up.  Will close this for now because yes, at some point, I'll have a proper website with optimized images.  Thank you!
